// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtBiADZ1NB03R8IiA6Lol9dPY46UHX_c',
    appId: '1:710896454620:web:680705c084bd31f8aa1d19',
    messagingSenderId: '710896454620',
    projectId: 'm-chat-f9364',
    authDomain: 'm-chat-f9364.firebaseapp.com',
    storageBucket: 'm-chat-f9364.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGBUAYfYnQOyDK89kxeKhLe_Vo5tJc2EU',
    appId: '1:710896454620:android:07644c41a56d1a57aa1d19',
    messagingSenderId: '710896454620',
    projectId: 'm-chat-f9364',
    storageBucket: 'm-chat-f9364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCksS_sRkoQmMbDlGEPdsZaVNBQWWxq8Tk',
    appId: '1:710896454620:ios:087a904936366993aa1d19',
    messagingSenderId: '710896454620',
    projectId: 'm-chat-f9364',
    storageBucket: 'm-chat-f9364.firebasestorage.app',
    iosBundleId: 'com.example.mChat',
  );
}
